[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["pythia"]

[project]
name = "pythia"
version = "0.1.0"
dependencies = [
    "matplotlib",
    "numdifftools",
    "numpy",
    "scipy",
    "pandas"
]